let cnchar = require('../../main');
let order = require('../order');
let trad = require('../trad');
let poly = require('../poly');
let draw = require('../draw');
let idiom = require('../idiom');
let xhy = require('../xhy');
let radical = require('../radical');
cnchar.use(order, trad, poly, draw, idiom, xhy, radical);
module.exports = cnchar;