const cnchar = require('../../main');
const order = require('../order');
const trad = require('../trad');
const poly = require('../poly');
const draw = require('../draw');
const idiom = require('../idiom');
const xhy = require('../xhy');
const radical = require('../radical');
cnchar.use(order, trad, poly, draw, idiom, xhy, radical);
module.exports = cnchar;