import cnchar from '../../main';
import order from '../order';
import trad from '../trad';
import poly from '../poly';
import draw from '../draw';
import idiom from '../idiom';
import xhy from '../xhy';
import radical from '../radical';
cnchar.use(order, trad, poly, draw, idiom, xhy, radical);
export default cnchar;